@TodoLists.Server_HostAddress = https://localhost:7240

POST {{TodoLists.Server_HostAddress}}/todo
###
PUT {{TodoLists.Server_HostAddress}}/todo/{id:int}
###
DELETE {{TodoLists.Server_HostAddress}}/todo/{id:int}
###
GET {{TodoLists.Server_HostAddress}}/todo/{id:int}
###
POST {{TodoLists.Server_HostAddress}}/todolist
###
GET {{TodoLists.Server_HostAddress}}/todolist
###
PUT {{TodoLists.Server_HostAddress}}/todolist/{id:int}
###
DELETE {{TodoLists.Server_HostAddress}}/todolist/{id:int}
###
GET {{TodoLists.Server_HostAddress}}/todolist/{id:int}
###
